---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBGyJe5m1vuL7RsfHJIBsFhN5QqTrztZfsVirHSWd83qCzjwqxjh4qgQb2t4BwQevGOXq1+9bWoBHU5fIg2KHCneB1R7O5BUThM2pi16qSbKxdmMa9BFe2835eRLNTo3zrK9SK1LMoEdN7rc0xO8jnRDCmw8UnFxw/uguVwF/xr9JECfkMXlG91ckbUQRdrL0t1bY9DoV4/tv7dD1/bkZvlSOJMrSjKrmiNIF2RK+P3locobzpi4rH5Kv2x3HDxyuKUnBCwqY5SSzQmQxcjMCypfTvq069IkgYaGhpYtggh4uvJbLt8tGabPjNQvqk8MzH12k2SjpkDxnQv0dtpJiw7/oGtTT+cdoS3zM9giWAkRLJD3Oi8YEyoA824QdpmJSPdxSkHHSxwW1+ZsMP7b1GmPjH4RY9mXftq+rz4UiDl5dY+fapNZBlhhYmV6A39l2mrSPRkX8axvTvxeVh5C5hzZc4b9BBn5xvAnJJ1MX8U8BXJsDlue/bVc/xucw6gCdWL3mOSpixjLCauQFJ8uriOtMj8lkP/zH2Uk+3eZav+l/UvbJRp6cCUto1VySH4gT0cbHXQfKT76xgyA495mCZ9iI0I8CK+7Chfa6K4D8TckI7XvvsziZo45CsrWPCufnysrOiZp7t8awAgAslfndUrmXiUbRY1H/HAezTjpiIcRCnX3eRiDO75Xmlz2BRSRidS+Ukgygw4BBnwZL8nOg==
    STRIPE_API_KEY: AgChrEZaGjsRLWJKIOpUjJEAjNrW7uhXPHJInlzEN+r7nz1UPN00ztSGEAHpwcgw5VISkGgNmViV9h4m+pXQhS0gwC10sDKB9CKEO2m3XYpsEZuYvt+bo6UYOn4jer5WNCS7ckdh5/V/J+oXKcR/PedxV8H0UPc/7Dpu1h8ObDbFR3FOOPfi8Iu/Xc88PPT8Iiuy6lQOHo8OC1gggznxC438kbCEEyFo4Y409Gj5YwW0KQz0YOel65PKviCZEK/kV2+O8S6EJZeh3dFEMa8VmKJy3O14aEGUwknhgP0Cg67mntXUGNj0akp1u1cd/IGnduWe1bqeRvFGpJ9PWhQHm8MZ7VhOyOn2lcQdAerttaLWDu1bV0moy97fG0YQeYT8EpEimBw+LbjP+Up+P5NtHrw7fQGBRr4gVtIfwh2qfjThKdbpn4kEgOkiejQd2ZUpTvitrey1xa5S0FzEPmaSz78V1VTy+wiF14ABEuHB+vfSRENbaAD89LQMy/g7e+OL18nljKcbIT7HGQ2miEOoDXR5MF1dSka+mSVVND7oFHzBa+rmTsywqCSkEGxyuuiTtcq9xMn2OcLMIVUqh+QFbCtwiYmQnWqTeXKQ0sSIchEqbDLCBV20A6S5AqSzqSFHBgw+QNiLaR3pChY6ubhQZY9gnPiFW5if6wAtDAzM0gSiG7YPqbI6tfp3Ckjsnt/PjDR5z3MY1Coq748=
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secret
      namespace: payments
    type: Opaque
