name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    - name: Build Docker Image
      run: |
        docker build -t ledger-api:latest ./app

    - name: Run Trivy Filesystem Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'

    - name: Run Semgrep
      continue-on-error: true
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/security-audit
